version: "2"
services:
  mongo:
    container_name: pim-backend-mongo-server
    image: mongo:latest
    expose:
      - "27017"

  pim-rpc-server:
    depends_on:
      - mongo
    container_name: pim-rpc-server
    build: ..
    links:
      - mongo
    ports:
      - "8888:8888"